import type { Metadata } from "next";
import "./globals.css";
import Inspect from "./Inspect";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <Inspect>
          {children}
        </Inspect>
      </body>
    </html>
  );
}
